anchors: #x, y, z are measured in mm
    - origin:       # should be at origin point
        id: 0x6754
        px: 0
        py: 0
        pz: 0
    - x_axis:       # defines x axis and y should be 0
        id: 0x674f
        px: 2400
        py: 0
        pz: 0
    - y_positive:   # defines the direction of y so y should be positive
        id: 0x6e5d
        px: 1200
        py: 10000
        pz: 490
    - anchor4:
        id: 0x6755
        px: 0
        py: 20000
        pz: 0
    - anchor5:
        id: 0x6742
        px: 2400
        py: 20000
        pz: 490


    # anchors = [DeviceCoordinates(0x6754, 1, Coordinates(0, 0, 490)),
    #            DeviceCoordinates(0x674f, 1, Coordinates(2400, 0, 0)),
    #            DeviceCoordinates(0x6e5d, 1, Coordinates(1200, 10000, 490)),
    #            DeviceCoordinates(0x6755, 1, Coordinates(0, 20000, 0)),
    #            DeviceCoordinates(0x6742, 1, Coordinates(2400, 20000, 490))]